const data = {
	products: [
		{
			_id: "1",
			name: "Nike slim Shirt",
			catgory: "Shirts",
			image: "/images/p1.jpg",
			price: 120,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "high qualty product",
		},
		{
			_id: "2",
			name: "Addidas fit Shirt",
			catgory: "Shirts",
			image: "/images/p2.jpg",
			price: 100,
			brand: "Nike",
			rating: 4.0,
			numReviews: 10,
			description: "high qualty product",
		},
		{
			_id: "3",
			name: "Lacoste Free Shirt",
			catgory: "Shirts",
			image: "/images/p3.jpg",
			price: 120,
			brand: "Lacoste",
			rating: 4.8,
			numReviews: 17,
			description: "high qualty product",
		},
		{
			_id: "4",
			name: "Nike slim pant",
			catgory: "Pants",
			image: "/images/p4.jpg",
			price: 130,
			brand: "Nike",
			rating: 4.5,
			numReviews: 14,
			description: "high qualty product",
		},
		{
			_id: "5",
			name: "Puma slim Pants",
			catgory: "Pants",
			image: "/images/p5.jpg",
			price: 65,
			brand: "Puma",
			rating: 4.5,
			numReviews: 10,
			description: "high qualty product",
		},
		{
			_id: "6",
			name: "Addidas Fit Pants",
			catgory: "Pants",
			image: "/images/p6.jpg",
			price: 139,
			brand: "Addidas",
			rating: 4.5,
			numReviews: 15,
			description: "high qualty product",
		},
	],
};
export default data;
